#!/usr/bin/env sh
#2.2.0
#2019-04-26

#Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#TODO
#merge {4,8}-chan-dl

w(){
	wget -r -H -D i.4cdn.org --hsts-file=/tmp/wget-hsts --https-only -e robots=off \
		--user-agent=Mozilla -nc -nd --accept=jpg,jpeg,png,gif,webm,mp4,pdf \
		-R "*s.jpg","*.html" "${link_get}"
}

dl(){
	if [ -n "$(echo ${board}|grep '\#')" ];then return;fi #skip comments
	if [ -n "$(echo ${board}|grep 'stop')" ];then exit;fi #exit when 'stop' is read as first argument
	loc="${dir}/${board}/${save}"
	url="https://boards.4chan.org/${board}/thread"
	if ! [ -d "${loc}" ];then mkdir -p "${loc}";fi
	cd "${loc}" || exit 1
	printf "Downloading ${board} ${thread} ${save}\n"
	link_get="${url}/${thread}"
	w
}

dir="${HOME}/downloads/chan/4chan"
. $(dirname "$0")/utils.sh
thread_list="${extra}/4chan-dl"

while getopts "beh" OPT;do
	case "$OPT" in
		b)
			while read -r board thread save;do
				dl
			done < "${thread_list}"
			exit;;
		e) $EDITOR "${thread_list}";exit;;
		h)
			printf "Example: ${0} <save dir> <link>\n"
			printf " -b\trun batch file\n"
			printf " -e\tedit ${thread_list}\n"
			printf " -h\tPrint this help\n"
			exit;;
	esac
done

if [ -z "${1}" ] || [ -z "${2}" ];then printf "Example: ${0} <save dir> <link>\n";exit;fi

if ! [ -d "./${1}" ];then mkdir "./${1}";fi
cd "${1}"
link_get="${2}"
w

