#!/usr/bin/env sh
#2.0.2
#2019-04-04

#Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

finish() { if [ -d "${tmpdir}" ];then rm --preserve-root -r "${tmpdir}";fi }
trap 'exit 1' INT HUP QUIT TERM USR1
trap finish EXIT
tmpdir=$(mktemp -d)

date=$(date "+%F-%H%M")
user="brandon"
group="${user}"
backup_dir="/mnt/data/backup"
comp="zstd"
V=""

dir_check(){ if ! [ -d "${target_dest}" ];then mkdir -p "${target_dest}";fi }
move_finish(){
	chown "${user}:${group}" "${tmpdir}/${target_comp}"
	mv -iv "${tmpdir}/${target_comp}" "${target_dest}"
}

hlp(){
	printf "\nGENERAL\n"
	printf " -h\tprint this help\n"
	printf " -v\tverbose tar\n"
	printf " -x\tuse xz\n"
	printf " -z\tuse zstd\n"
	printf "\nCOMPRESS\n"
	printf " -1\tchromium\n"
	printf " -2\thome-bin\n"
	printf " -3\thome-config\n"
	printf " -4\thome-local\n"
	printf " -5\tetc\n"
	printf " -6\tvnstat\n"
}

mode="${0##*/backup-}"
while getopts "123456hvxz" OPT;do
	case "$OPT" in
		1) mode="chromium";;
		2) mode="home-bin";;
		3) mode="home-config";;
		4) mode="home-local";;
		5) mode="etc";;
		6) mode="vnstat";;
		v) V="v";;
		x) comp="xz";;
		z) comp="zstd";;
		h) hlp;exit;;
	esac
done

case "${comp}" in
	zstd) C="zstd";A="-T0";E="zst";;
	xz) C="xz";A="-e9";E="xz";;
esac

case "${mode}" in
	chromium)
		target_source="${HOME}/.config/chrome"
		target_dest="${backup_dir}/${user}/chromium-profiles/${date}"
		dir_check
		cd "${target_source}"
		for f in *chrom*;do
			target_comp="${date}-${user}-${f}.tar.${E}"
			tar \
				--exclude="${f}/Default/File System" \
				--xattrs --sparse -${V}cf - "${f}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
			move_finish
		done
		;;
	home-config)
		target_comp="${user}-config-${date}.tar.${E}"
		target_source="${HOME}/.config"
		target_dest="${backup_dir}/${user}/config"
		dir_check
		tar \
			--exclude="${target_source}/*chrom*" \
			--exclude="${target_source}/rtorrent/session/*" \
			--exclude="${target_source}/transmission/resume/*" \
			--exclude="${target_source}/transmission/torrents/*" \
			--exclude="${target_source}/kernel/src/*" \
			--exclude="${target_source}/kernel/distfiles/*" \
			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
		;;
	home-local)
		target_comp="${user}-local-${date}.tar.${E}"
		target_source="${HOME}/.local"
		target_dest="${backup_dir}/${user}/local"
		dir_check
		tar \
			--exclude="${target_source}/share/Trash/*" \
			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
		move_finish
		;;
	etc)
		target_comp="etc-${date}.tar.${E}"
		target_source="/etc"
		target_dest="${backup_dir}/etc"
		dir_check
		tar \
			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
		move_finish
		;;
	home-bin)
		target_comp="${date}-${user}-bin.tar.${E}"
		target_source="${HOME}/.bin"
		target_dest="${backup_dir}/${user}/bin"
		dir_check
		mkdir "${tmpdir}"/bin
		cp -r "${target_source}" "${tmpdir}/bin"
		cd "${tmpdir}"
		tar \
			--xattrs --sparse -${V}cf - "${target_source}" -P | "$C" "$A" >| "${tmpdir}/${target_comp}"
		rm -rf "${tmpdir}/bin"
		move_finish
		;;
	vnstat)
		year=$(date "+%Y")
		month=$(date "+%m")
		day=$(date "+%d")
		target_source="${HOME}/.config/vnstat/vnstat.db"
		target_dest="${backup_dir}/vnstat-database"
		mkdir -p "${target_dest}/${year}/${month}/${day}"
		cp "${target_source}" "${target_dest}/${year}/${month}/${day}"
		;;
	meta) hlp;exit;;
esac
