#!/bin/sh
#3.0.0
#2018-12-08

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

hlp(){
	printf " -1\tsha1\n"
	printf " -2\tsha224\n"
	printf " -3\tsha256\n"
	printf " -4\tsha384\n"
	printf " -5\tsha512\n"
	printf " -6\tmd5\n"
	printf " -c\tforce checksum\n"
	printf " -h\tprint this help\n"
	printf " -r\tforce rename\n"
}

if [ -z "${1}" ];then hlp;exit;fi
while true;do
	case "${1}" in
		-1) h="sha1";break;;
		-2) h="sha224";break;;
		-3) h="sha256";break;;
		-4) h="sha384";break;;
		-5) h="sha512";break;;
		-6) h="md5";break;;
		-c) mode="checksum";shift;;
		-r) mode="rename-checksum";shift;;
		-h) hlp;exit;;
		*) break;;
	esac
done

mode="${0##*/}"
case "${mode}" in
	checksum) find . -type f -print0 | nice -19 xargs --max-args=1 --max-procs=$(($(nproc)+1)) --null ${h};;
	rename-checksum)
		for f in *;do
			if [ -f "${f}" ];then "${h}" "${f}" | sed -e 's/\([^ ]*\) \(.*\(\..*\)\)$/mv -v \2 \1\3/e';fi
		done
		;;
esac

