#!/bin/sh
#2.1.0
#2018-10-12

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

sha1="0"
sha224="0"
sha256="0"
sha384="0"
sha512="0"
md5="0"

hlp(){
	printf " -1\tsha1\n"
	printf " -2\tsha224\n"
	printf " -3\tsha256\n"
	printf " -4\tsha384\n"
	printf " -5\tsha512\n"
	printf " -6\tmd5\n"
	printf " -h\tprint this help\n"
}

if [ -z "${1}" ];then hlp;return;fi
while true;do
	case "${1}" in
		-1) mode="sha1";break;;
		-2) mode="sha224";break;;
		-3) mode="sha256";break;;
		-4) mode="sha384";break;;
		-5) mode="sha512";break;;
		-6) mode="md5";break;;
		-h) hlp;return;;
		*) break;;
	esac
done

case "${mode}" in
	sha1) h="/usr/bin/sha1";;
	sha224) h="/usr/bin/sha224";;
	sha256) h="/usr/bin/sha256";;
	sha384) h="/usr/bin/sha384";;
	sha512) h="/usr/bin/sha512";;
	md5) h="/usr/bin/md5";;
	*) exit;;
esac

find . -type f -print0 | nice -19 xargs --max-args=1 --max-procs=$(($(nproc)+1)) --null "${h}"
