#!/bin/sh
#4.0.0
#2018-11-07

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$(id -u)" -eq 0 ];then printf "Do not run as root\n";exit;fi

cache_rm(){
	cache="${XDG_CACHE_HOME}/${data##*/}"
	if [ -d "${cache}" ];then
		sleep 3
		rm -rf "${cache}"
	fi
}

launch(){ ${ver} --user-data-dir="${data}"; }

#ver="chromium"
ver="google-chrome-unstable"
config="${HOME}/.config/chrome/${ver}"
mode="${0##*/}"
case "${mode}" in
	chromium-default)
		data="${config}-default"
		launch
		cache_rm
		;;
	chromium-ex1)
		data="${config}-ex1"
		launch
		cache_rm
		;;
	chromium-ex2)
		data="${config}-ex2"
		launch
		cache_rm
		;;
	chromium-ex3)
		data="${config}-ex3"
		launch
		cache_rm
		;;
	chromium-sandbox)
		finish(){ if [ -d "${data}" ];then rm --preserve-root -r "${data}";fi }
		trap 'exit 1' INT HUP QUIT TERM USR1
		trap finish EXIT
		data=$(mktemp -d)
		launch
		;;
esac
