#!/bin/sh
#3.3.0
#2018-10-14

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

cache_rm(){
	if [ -d "${XDG_CACHE_HOME}/${data##*/}" ];then
		sleep 5
		rm -rf "${XDG_CACHE_HOME}/${data##*/}"
	fi
}

launch(){
	/usr/lib64/chromium-browser/chromium-launcher.sh --user-data-dir="${data}"
}

mode="${0##*/}"
case "${mode}" in
	chromium-default)
		data="/home/brandon/.config/chromium-default"
		launch
		cache_rm
		;;
	chromium-ex)
		data="/home/brandon/.config/chromium-ex"
		launch
		cache_rm
		;;
	chromium-ex2)
		data="/home/brandon/.config/chromium-ex2"
		launch
		cache_rm
		;;
	chromium-sandbox)
		finish(){ if [ -d "${data}" ];then rm --preserve-root -r "${data}";fi }
		trap 'exit 1' INT HUP QUIT TERM USR1
		trap finish EXIT
		data=$(mktemp -d)
		chmod 755 "${data}"
		launch
		;;
esac
