#!/usr/bin/env sh
#2.0.0
#2018-09-21

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

file_count(){
	cnt=$(find ${D} -maxdepth 1 -type f -size +${lower} -size -${upper} | wc -l)
	if ! [ "${cnt}" = "0" ];then printf "${lower}-${upper}  \t: ${cnt}\n";fi
	unset cnt lower upper
}

if [ -n "${1}" ];then D="${1}";else D=".";fi

lower="0k"
upper="10M"
file_count

lower="10M"
upper="100M"
file_count

lower="100M"
upper="150M"
file_count

lower="150M"
upper="200M"
file_count

lower="200M"
upper="500M"
file_count

lower="500M"
upper="1G"
file_count

lower="1G"
upper="10G"
file_count

lower="10G"
upper="100G"
file_count
