#!/bin/sh
#2.3.0
#2018-09-11

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

hlp(){
	printf " -a\trun for the entire repo\n"
	printf " -h\tprint this help\n"
}

mode="single"
while true;do
	case "${1}" in
		-a) mode="repo";shift;;
		-h) hlp;return;;
		*) break;;
	esac
done

case "${mode}" in
	single)
		e=$(ls -1A *.ebuild|tail -n1)
		ebuild ${e} manifest
		;;
	repo)
		find . -maxdepth 2 -mindepth 2 -path '*/*' -type d -exec dash -c "cd '{}' && ${0}" \;
		;;
esac
