#!/bin/sh
#3.1.0
#2018-12-16

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$(id -u)" -ne 0 ];then printf "Requires root\n";exit;fi

for f in /dev/disk/by-id/ata-*;do
	if ! [ "$(echo ${f}|grep part)" ];then
		len=$(echo ${f##*/}|wc -m)
		temp=$(smartctl -a ${f}|grep Celsius|awk '{print $10}')
		case "${len}" in
			3[2-9]|40) tab="\t\t\t";;
			4[0-8]) tab="\t\t";;
			[1-3][0-1]) printf "below lower format\nlen: ${len}\ndevice: ${f}";;
			[4-9][7-9]) printf "above upper format\nlen: ${len}\ndevice: ${f}";;
		esac
		printf "${f}${tab}${temp}°c\n"
	fi
done
