#!/bin/sh
#2.3.0
#2018-05-17

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$(id -u)" -ne 0 ];then printf "Requires root, exiting.\n";return;fi

raidz1() {
drives="
ata-HGST_HDN724030ALE640_PK2234P9K6UPAY
ata-HGST_HDN724030ALE640_PK2234P9K6TEZY
ata-HGST_HDN724030ALE640_PK2234P9K6TGTY
ata-HGST_HDN724030ALE640_PK2234P9K5M9RY
ata-WDC_WD3003FZEX-00Z4SA0_WD-WMC130D5ZX4M
"
}
raidz2() {
drives="
ata-WDC_WD3003FZEX-00Z4SA0_WD-WMC130D2M3CW
ata-HGST_HDN724030ALE640_PK2234P9K6UNNY
ata-HGST_HDN724030ALE640_PK2234P9K6MJKY
ata-HGST_HDN724030ALE640_PK2234P9K6UNEY
ata-WDC_WD3003FZEX-00Z4SA0_WD-WMC130D87881
"
}

mirror(){
drives="
ata-HGST_HDN726060ALE610_K1G07K0B
ata-WDC_WD60EFRX-68MYMN1WD-WX11DC449RFA
"
}

#extra spaces are to ofset tab so they line up right. ie comp for diff drive name length
temp() {
	for f in ${drives}; do
		temp=$(smartctl -a /dev/disk/by-id/"${f}"|grep Celsius|awk '{print $10}')
		if ! [ "${f}" = "ata-HGST_HDN726060ALE610_K1G07K0B" ];then
			printf "%s   \t%s°C\n" "${f}" "${temp}"
		else
			printf "%s   \t\t%s°C\n" "${f}" "${temp}"
		fi
	done
}

printf "STORAGE POOL\n"
printf "RAIDZ-1\n"
raidz1;temp
printf "RAIDZ-2\n"
raidz2;temp
printf "MIRROR\n"
mirror;temp
