#!/bin/sh
#1.5.0
#2019-01-13
#original unknown
#modified by, Brandon Zorn, brandonzorn@cock.li
while true;do
	if [ -f "${1}" ];then
		case "${1}" in
			*.tgz|*.tbz2) tar xvf "${1}";;
			*.txz) tar xvJf "${1}";;
			*.tar.bz2) tar xvjf "${1}";;
			*.tar.gz) tar xvzf "${1}";;
			*.tar.xz) tar xvJf "${1}";;
			*.tar.zst) zstd -dc "${1}"|tar xvf -;;
			*.tar.lz4) lz4 -dc "${1}"|tar xvf -;;
			*.tar.lzma) tarlzma xvf "${1}";;
			*.tar.lrz) lrzuntar "${1}";;
			*.rar|*.RAR) unrar "${1}";;
			*.gz) gunzip -k "${1}";;
			*.xz) unxz -k "${1}";;
			*.bz2) bzip2 -dk "${1}";;
			*.zst) unzstd -d "${1}";;
			*.tar) tar xvf "${1}";;
			*.zip) unzip "${1}";;
			*7z|*.iso|*.ISO) 7z x "${1}";;
			*.cbz|*.cbr) 7z x "${1}" -o"${1}";;
			*) printf "cannot extract: ${1}\n";;
		esac
	else
		printf "not a valid file: ${1}\n"
	fi
	if [ -n "${2}" ];then shift;else break;fi
done
