#!/usr/bin/env python3
# 1.2.0
# 2020-09-20

# Copyright (C) 2020 Brandon Zorn <brandonzorn@cock.li>
#
# This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.

# TODO
#   output dir for all compressors
#   implement extraction to a subdirectory

import argparse
from pathlib import Path

from utils import utils


class Decompress:
    def __init__(self):
        self.__input_files = None
        self.__output_dir = None
        self.__files = False
        self.__subdir_extract = False

    def run_extraction(self, filename: str):
        if filename.endswith(('.tar.bz2', '.tbz2')):
            utils.run_cmd(f'tar -xvjf "{filename}"')

        elif filename.endswith(('.tar.gz', '.tgz')):
            utils.run_cmd(f'tar -xvzf "{filename}"')

        elif filename.endswith(('.tar.xz', '.txz')):
            utils.run_cmd(f'tar -xvJf "{filename}"')

        elif filename.endswith('.tar.zst'):
            utils.run_cmd(f'zstd -dc --long=31 \'{filename}\' | tar xvf -', sh_wrap=True)

        elif filename.endswith('.tar.lz4'):
            utils.run_cmd(f'lz4 -dc \'{filename}\' | tar xvf -', sh_wrap=True)

        elif filename.endswith('.tar.lzma'):
            utils.run_cmd(f'tarlzma -xvf "{filename}"')

        elif filename.endswith('.tar.lrz'):
            utils.run_cmd(f'lrzuntar "{filename}"')

        elif filename.endswith(('.rar', 'RAR', '.cbr')):
            utils.run_cmd(f'unrar "{filename}"')

        elif filename.endswith('.gz'):
            utils.run_cmd(f'gunzip -k "{filename}"')

        elif filename.endswith('.xz'):
            utils.run_cmd(f'unxz -k "{filename}"')

        elif filename.endswith('.bz2'):
            utils.run_cmd(f'bzip2 -dk "{filename}"')

        elif filename.endswith('.zst'):
            utils.run_cmd(f'unzstd -d --long=31 "{filename}"')

        elif filename.endswith('.tar'):
            utils.run_cmd(f'tar -xvf "{filename}"')

        elif filename.endswith(('.zip', '.cbz')):
            utils.run_cmd(f'unzip "{filename}"')

        elif filename.endswith(('.7z', 'iso', 'ISO')):
            utils.run_cmd(f'7z x "{filename}"')

        else:
            print(f'cannot extract: \'{filename}\'')

    def get_files(self):
        if self.__files:
            dir_listing = []
            for f in Path(Path.cwd()).iterdir():
                dir_listing.append(str(f))

            for f in dir_listing:
                if Path.is_file(Path(f)) and self.__files:
                    self.run_extraction(filename=f)
        elif self.__input_files is not None:
            for f in self.__input_files:
                if Path.is_file(Path(f)):
                    self.run_extraction(filename=f)

    def run(self, args):
        # decompression type
        if args.files:
            self.__files = True
        if args.subdir:
            self.__subdir_extract = True
        # other
        if args.input_files is not None:
            self.__input_files = args.input_files
        if args.output_dir:
            out = Path.resolve(Path(args.output_dir))
            if not Path.is_dir(out):
                if Path.exists(out):
                    utils.die(msg=f'selected output dir \'{out}\' exists but is not a directory')
                Path(out).mkdir(parents=True, exist_ok=True)
            self.__output_dir = out

            # TODO
            #   need to plumb into decompressors
            raise NotImplementedError

        self.get_files()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('input_files',
                        action='store',
                        type=str,
                        nargs='*',
                        default=None,
                        help=argparse.SUPPRESS)
    parser.add_argument('-f', '--files',
                        action='store_true',
                        help='decompress all files in cwd')
    parser.add_argument('-o', '--output-dir',
                        metavar='DIR',
                        help='create the archive[s] in this directory')
    opts = parser.add_argument_group('EXTRACTION OPTIONS')
    opts.add_argument('-s', '--subdir',
                      action='store_true',
                      help='Extract archive to a directory created from filename, only cb{r,z} and iso')

    args = parser.parse_args()

    utils.args_required_else_help()

    run = Decompress()
    run.run(args)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit
