#!/bin/sh
#1.3.0
#2018-09-08
#original unknown
#modified by, Brandon Zorn, brandonzorn@cock.li
if [ -f ${1} ];then
	case ${1} in
		#*.) tar ${1};;
		*.tgz) tar xvf ${1};;
		*.txz) tar xvJf ${1};;
		*.tbz2) tar xvf ${1};;
		*.tar.bz2) tar xvjf ${1};;
		*.bz2) bzip2 -dk ${1};;
		*.tar.gz) tar xvzf ${1};;
		*.tar.xz) tar xvJf ${1};;
		*.tar.lzma) tar --lzma xvf ${1};;
		*.rar) unrar ${1};;
		*.gz) gunzip ${1};;
		*.tar) tar xvf ${1};;
		*.zip) unzip ${1};;
		*.iso) 7z x ${1};;
		*.ISO) 7z x ${1};;
		*.7z) 7z x ${1};;
		*.tar.lrz) lrzuntar ${1};;
		*.cbz) 7z x ${1} -o"${1}";;
		*.cbr) 7z x ${1} -o"${1}";;
		*) printf "'${1}' cannot be extracted via >extract<\n";;
	esac
else
	printf "'${1}' is not a valid file\n"
fi
