#!/usr/bin/env sh
#1.0.0
#2019-12-04

#Copyright (C) 2019 Brandon Zorn <brandonzorn@cock.li>
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$(id -u)" -ne 0 ];then die "Requires root";fi

die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }

no_live="1"
edit="0"
pkg=""

while getopts "f:leh" OPT;do
	case "$OPT" in
		l)
			no_live="0"
			;;
		e)
			edit="1"
			;;
		f)
			pkg="${OPTARG}"
			;;
		h)
			printf "GENERAL\n"
			printf " -h\tPrint this help\n"
			printf " -e\tedit ebuild once copied\n"
			printf " -f\tcopy ebuild from gentoo repo to local repo\n"
			printf " -l\tcopy live ebuild from gentoo repo to local repo\n"
			exit;;
	esac
done
shift $((OPTIND - 1))

repo_gentoo="$(grep location /etc/portage/repos.conf/gentoo.conf|awk '{print $3}')"
repo_local="$(grep location /etc/portage/repos.conf/local.conf|awk '{print $3}')"

repo_local_path="${repo_local}/${pkg}"
repo_gentoo_path="${repo_gentoo}/${pkg}"

if ! [ -d "${repo_gentoo_path}" ];then
	die "supplied pkg is invalid: ${pkg}"
fi

if ! [ -d "${repo_local_path}" ];then
	mkdir -pv "${repo_local_path}"
fi

if [ "${no_live}" = "1" ];then
	pkg_wanted="$(ls -1A --ignore=*xml --ignore=Manifest --ignore=*9999* "${repo_gentoo_path}"|sort -V|tail -n1)"
else
	pkg_wanted="$(ls -1A --ignore=*xml --ignore=Manifest "${repo_gentoo_path}"|sort -V|tail -n1)"
fi

cp -a "${repo_gentoo_path}/${pkg_wanted}" "${repo_local_path}" || die "failed to copy ebuild: ${pkg_wanted}"

if [ -f "${repo_gentoo_path}/metadata.xml" ];then
	cp -a "${repo_gentoo_path}/metadata.xml" "${repo_local_path}" || die "failed to copy metadata.xml"
fi

if [ -d "${repo_gentoo_path}/files" ];then
	cp -av "${repo_gentoo_path}/files" "${repo_local_path}" || die "failed to copy files dir"
fi

if [ "${edit}" = "1" ];then
	"${EDITOR}"  "${repo_local}/${pkg}/${pkg_wanted}"
fi

cd "${repo_local_path}"
digest-ebuild

