#!/bin/sh
#0.2.0
#2018-09-15

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ -z "${1}" ];then
	printf "Enter ELF path\n"
	read e
else
	e="${1}"
fi

l=$(ldd ${e}|awk '{print $1}'|awk '$1=$1' ORS=' ')
echo $l

echo
echo
echo Use 'equery d' to find deps. WIP

#for f in $l;do
#	equery b "${f}"
#done

#equery b "${l}"
