#!/usr/bin/env sh
#1.1.0
#2020-03-11

#Copyright (C) 2020 Brandon Zorn <brandonzorn@cock.li>
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }

no_live="1"
pkg=""

if [ -z "${1}" ];then "${0}" -h;exit;fi
while getopts "f:Elehx" OPT;do
	case "$OPT" in
		l)
			no_live="0"
			;;
		f)
			pkg="${OPTARG}"
			;;
		x)
			pkg="$(xclip -o)"
			;;
		h)
			printf "GENERAL\n"
			printf " -h\tPrint this help\n"
			printf " -f\tget pkg from \$1\n"
			printf " -l\tenable diffing live ebuild, otherwise ignores them\n"
			printf " -x\tget pkg from clipboard\n"
			exit;;
		*) printf "Showing help\n\n";"${0}" -h;;
	esac
done
shift $((OPTIND - 1))

repo_gentoo="$(grep location /etc/portage/repos.conf/gentoo.conf|awk '{print $3}')"
repo_local="$(grep location /etc/portage/repos.conf/local.conf|awk '{print $3}')"

repo_local_path="${repo_local}/${pkg}"
repo_gentoo_path="${repo_gentoo}/${pkg}"

if ! [ -d "${repo_gentoo_path}" ];then
	die "supplied pkg is invalid: ${pkg}"
fi

if [ "${no_live}" = "1" ];then
	pkg_gentoo="$(ls -1A --ignore=*xml --ignore=Manifest --ignore=*9999* "${repo_gentoo_path}"|sort -V|tail -n1)"
	pkg_local="$(ls -1A --ignore=*xml --ignore=Manifest --ignore=*9999* "${repo_local_path}"|sort -V|tail -n1)"
else
	pkg_gentoo="$(ls -1A --ignore=*xml --ignore=Manifest "${repo_gentoo_path}"|sort -V|tail -n1)"
	pkg_local="$(ls -1A --ignore=*xml --ignore=Manifest "${repo_local_path}"|sort -V|tail -n1)"
fi

if [ -z "${pkg_gentoo}" ] || [ -z "${pkg_gentoo}" ];then die "No ebuilds found for: ${pkg}";fi

diff -Naur "${repo_gentoo_path}/${pkg_gentoo}" "${repo_local_path}/${pkg_local}"

