#!/bin/sh
#1.2.1
#2018-11-02

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

hlp(){
	printf "No flag will be standard 'equery b' output\n"
	printf " -e\tPrint emergable list\n"
	printf " -h\tprint this help\n"
	printf " -l\tPrint sorted with versions\n"
	printf " -n\tPrint sorted no version list, package.*\n"
}

main(){
	equery b $(ldd ${elf}|awk '{print $1}'|awk '$1=$1' ORS=' ')
}

mode="list"
while true;do
	case "${1}" in
		-l) mode="list_sort";shift;;
		-n) mode="list_nover";shift;;
		-e) mode="list_emerge";shift;;
		-h) hlp;exit;;
		*) break;;
	esac
done

if [ -n "${1}" ];then
	elf="${1}"
else
	printf "Enter ELF path\n"
	read elf
fi

fileinfo=$(file ${elf})
if [ -z "$(echo ${fileinfo}|grep ELF)" ];then
	printf "Entered file is not marked as ELF\n"
	exit 1
elif [ -n "$(echo ${fileinfo}|grep statically)" ];then
	printf "Entered ELF file statically linked\n"
	exit 1
fi

case "${mode}" in
	list)
		main
		;;
	list_sort)
		main|awk '{print $1}'|sort -u
		;;
	list_nover)
		main|awk '{print $1}'|sort -u|sed 's/-r[0-9]//;s/-[^-]*$//'
		;;
	list_emerge)
		main|awk '{print $1}'|sort -u|sed 's/-r[0-9]//;s/-[^-]*$//'|awk '$1=$1' ORS=' '
		;;
esac
