#!/bin/bash
#1.0.0
#2018-02-20
#req bash

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#TODO
#make less shit
#auto get current # of packages instead of hard coded

list=$(eix -Ic|grep "\[[A-Z]"|awk '{print $2}')

get_spot() {
	list_cur=$(printf "${list}\n"|head -n"${f}"|tail -n1)
}

main() {
	for f in {1..853};do
		printf "Package #$f of xxx\n"
		get_spot
		eix "${list_cur}"
	done
}

main
