#!/bin/sh
#1.2.0
#2018-10-04

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

printf "Someone fucked up the boot loader again\n\n"
g=$(grub-install --target=x86_64-efi --efi-directory=/boot/efi)
f=$(echo ${g}|grep error)

if [ -n "${f}" ];then
	printf "Error stopping\n"
	exit 1
else
	printf "${g}\n\n"
	grub-mkconfig -o /boot/grub/grub.cfg
fi
