#!/bin/sh
#3.1.0
#2018-12-08

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ $(id -u) -ne 0 ]; then printf "Requires root, exiting.\n";exit;fi
finish(){ if [ -d "${tmpdir}" ];then rm --preserve-root -r "${tmpdir}";fi }
trap 'exit 1' INT HUP QUIT TERM USR1
trap finish EXIT
tmpdir=$(mktemp -d)

clean(){
	mv .config ${tmpdir}
	make distclean
	mv ${tmpdir}/.config .
}

kdir="/usr/src/linux"

while true;do
	case "${1}" in
		-r)
			for f in ${kdir}*;do
				rm -rf "${f}"
			done
			exit;;
		-c)
			cd ${kdir} || exit
			clean
			exit;;
		-C)
			for f in ${kdir}-*;do
				cd ${f} || exit
				clean
			done
			exit;;
		-h)
			printf " -c\tclean only /usr/src/linux symlink\n"
			printf " -C\tclean /usr/src/linux-*\n"
			printf " -h\tprint this help\n"
			printf " -r\tremove all /usr/src/linux*\n"
			exit;;
		*) printf "Nothing to do, for options see -h\n";exit;;
	esac
done
