#!/usr/bin/env python3
# 3.2.1
# 2020-05-06

# Copyright (C) 2018,2019,2020 Brandon Zorn <brandonzorn@cock.li>
#
# This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.

import shutil
from pathlib import Path

from tempfile import TemporaryDirectory

from utils import utils


def main():
    utils.is_root()

    with TemporaryDirectory() as tmpdir:
        cfgold = Path('/boot/grub/grub.cfg')
        cfgnew = Path() / tmpdir / 'grub.cfg'

        cmd = f'grub-mkconfig -o {cfgnew}'
        utils.run_cmd(cmd)

        if not Path.is_file(cfgnew):
            utils.die(msg='grub did not create new cfg file')

        if not utils.hash_compare_sha1(cfgold, cfgnew):
            Path.unlink(cfgold)
            shutil.move(cfgnew, cfgold)
        else:
            # print('No changes')
            pass


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit()
