#!/bin/sh
#1.0.0
#2018-05-17

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#TODO
#clean pattern

if [ $(id -u) -ne 0 ]; then printf "Requires root, exiting.\n";return;fi

lst="1"
rem="0"
pat="0"

b="/boot"

o=$(ls -1A ${b}|grep old)

hlp() {
	printf " -h\tprint this help\n"
	printf " -l\tList found\n"
	printf " -p\tUse pattern/glob\n"
	printf " -r\tRemove found\n"
}

while true;do
	case "${1}" in
		-l) lst="1";shift;;
		-r) rem="1";shift;;
		-p) pat="1";shift;;
		-h) hlp;return;;
		*) break;;
	esac
done

if [ -n "${o}" ] && ! [ "${pat}" = "1" ];then
	if [ "${lst}" = "1" ];then
		ls -1A "${b}"/v*old
	fi
	if [ "${rem}" = "1" ];then
		rm "${b}"/*old
	fi
elif ! [ "${pat}" = "1" ];then
	printf "No old kernel vmlinuz images found\n"
	return
fi

if [ "${pat}" = "1" ];then
	printf "Enter kernel version to remove\n"
	read v
	rm "${b}"/*"${v}"* || return
fi
