#!/usr/bin/env sh
#1.1.0
#2019-05-17

#Copyright (C) 2019 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

die(){ /bin/echo -e "\033[0;31m$*\033[m";exit 1; }

if [ "$(id -u)" -ne 0 ]; then die "Requires root, exiting.";fi

if ! [ -f "/usr/src/linux/usr/gen_init_cpio" ];then die "Make sure the kernel is build first";fi

ksym="/usr/src/linux"
kdir="$(readlink -f ${ksym})"
kver="$(echo ${kdir##*/linux-})"

dracut --compress=lz4 --hostonly '' "${kver}"
