#!/bin/sh
#2.3.0
#2018-12-04

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ $(id -u) -ne 0 ]; then printf "Requires root, exiting.\n";exit;fi

hlp() {
	printf "GENERAL\n"
	printf " -h\tPrint this help\n"
	printf " -V\tverbose emerge\n"
	printf "\nKERNELS\n"
	printf " -G\tinstall sys-kernel/gentoo-sources [default]\n"
	printf " -g\tinstall sys-kernel/git-sources\n"
	printf " -v\tinstall sys-kernel/vanilla-sources\n"
}

mode="gentoo"
v="--quiet"

while true;do
	case "${1}" in
		-h) hlp;exit;;
		-V) v="--verbose";shift;;
		-G) mode="gentoo";shift;;
		-g) mode="git";shift;;
		-v) mode="vanilla";shift;;
		*) break;;
	esac
done

case "${mode}" in
	gentoo) emerge --ignore-default-opts --oneshot ${v} sys-kernel/gentoo-sources;;
	git) emerge --ignore-default-opts --oneshot ${v}  sys-kernel/git-sources;;
	vanilla) emerge --ignore-default-opts --oneshot ${v} sys-kernel/vanilla-sources;;
esac

if [ -f "/proc/config.gz" ];then
	printf "Installing running kernel config\n"
	zcat /proc/config.gz >| /usr/src/linux/.config
fi
