#!/bin/bash
#1.0.0
#2018-10-20

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#TODO
#no same numbers
#compare to previous winning nmbers and remove if match -- to much work
#win

#i trust my own rng over big-lottos rng

#mega millions
a="71" #70
b="26" #25

count="0"

rand(){ r="$RANDOM"; }

main(){
	rand
	if (( $r < $a ));then
		echo $r
	else
		rand
		main
	fi
	count=$((count+1))
}

main2(){
	rand
	if (( $r < $b ));then
		echo $r
	else
		rand
		main
	fi
	count=$((count+1))
}

echo Winning numbers are :
main
main
main
main
main
main2

echo Times run : $count

