#!/bin/sh
#1.0.0
#2019-03-02

#Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#not really portable, more qol

#TODO
#flags
#everything else
#will take backbone of lxd-admin for state checking and other qol things

printf "Stoping master"
lxd stop dev-gentoo-clang-minimal

printf "stoping subs"
lxd stop base-gentoo-rutorrent
lxd stop base-gentoo-transmission

printf "deleting subs"
lxd delete base-gentoo-rutorrent
lxd delete base-gentoo-transmission

printf "copying master to subs"
lxd copy dev-gentoo-clang-minimal base-gentoo-rutorrent
lxd copy dev-gentoo-clang-minimal base-gentoo-transmission

printf "starting subs"
lxd start base-gentoo-rutorrent
lxd start base-gentoo-transmission

lxd exec base-gentoo-rutorrent /root/setup-rutorrent
lxd exec base-gentoo-transmission /root/setup-transmission

lxd exec base-gentoo-rutorrent crontab -e
lxd exec base-gentoo-transmission crontab -e

printf "stoping subs"
lxd stop base-gentoo-rutorrent
lxd stop base-gentoo-transmission

printf "Done"


