#!/bin/sh
#1.6.0
#2018-10-14

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#TODO
#fix -A

mime_type_image(){
	if [ -d "${f}" ];then return;fi
	total=$((total+1))
	mimeext=$(file -b --mime-type -- "${f%%}"|awk '{print $NF}' FS=/)
	if ! [ "${mimeext}" = "jpeg" ] && ! [ "${mimeext}" = "png" ] && ! [ "${mimeext}" = "gif" ];then return;fi
	ext="${f##*.}"
	if [ "${mimeext}" = "jpeg" ] && [ "${ext}" = "jpg" ];then return;fi
	if ! [ "${mimeext}" = "${ext}" ];then
		if [ "${mimeext}" = "jpeg" ];then mimeext="jpg";fi
		if [ -f "${f%%.*}.${mimeext}" ] && [ -f "${f%%.*}.${ext}" ];then
			printf "File collision : $(readlink -f ${f%%})\n"
			coll=$((coll+1))
			return
		else
			printf "Mismatch : $(readlink -f ${f%%})\n"
		fi
		if [ "${listonly}" = "1" ];then return;fi
		mv "${f%%}" "${f%%.*}.${mimeext}"
		fixed=$((fixed+1))
	fi
}

while true;do
	case "${1}" in
		-I)
			total="0"
			coll="0"
			fixed="0"
			listonly="0"
			for f in *;do mime_type_image;done
			if ! [ "${total}" = "0" ];then printf "Checked : ${total}\tCorrected : ${fixed}\tCollisions : ${coll}\tin : ${PWD}\n";fi
			break;;
		-L)
			total="0"
			listonly="1"
			for f in *;do mime_type_image;done
			if ! [ "${total}" = "0" ];then printf "Checked : ${total} \tCollisions : ${coll}\tin : ${PWD}\n";fi
			break;;
		-A)
			printf "Checking file mime info\n"
			find . -type d -exec sh -c 'cd "{}" && /usr/local/bin/mime-correct -I' \;
			break;;
		*)
			printf "Invalid selection\n"
			printf " -A\trun in all sub-dirs of \$PWD\n"
			printf " -I\trun in single dir only\n"
			printf " -L\tlist only, no corrections\n"
			break;;
	esac
done
