#!/bin/sh
#1.8.1
#2018-11-16

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#ref
#collision -- same filename when corrected
#mismatch -- wrong file extension

mime_type_image(){
	if [ -d "${f}" ];then return;fi
	total=$((total+1))
	mimeext=$(file -b --mime-type -- "${f%%}"|awk '{print $NF}' FS=/)
	if ! [ "${mimeext}" = "jpeg" ] && ! [ "${mimeext}" = "png" ] && ! [ "${mimeext}" = "gif" ];then return;fi
	ext="${f##*.}"
	if [ "${mimeext}" = "jpeg" ] && [ "${ext}" = "jpg" ];then return;fi
	if ! [ "${mimeext}" = "${ext}" ];then
		if [ "${mimeext}" = "jpeg" ];then mimeext="jpg";fi
		if [ -f "${f%%.*}.${mimeext}" ] && [ -f "${f%%.*}.${ext}" ];then
			if [ "${V}" = "1" ];then
				if [ "$(sha1sum ${f%%.*}.${mimeext}|awk '{print $1}')" = "$(sha1sum ${f%%.*}.${ext}|awk '{print $1}')" ];then
					printf "File collision is same file : ${f%%.*}.${mimeext} ${f%%.*}.${ext}\n"
					#TODO
					#remove wrong ext file, since they are the same?
				else
					printf "File collision with different files : ${f%%.*}.${mimeext} ${f%%.*}.${ext}\n"
				fi
			fi
			coll=$((coll+1))
			return
		else
			if [ "${V}" = "1" ];then printf "Mismatch : $(readlink -f ${f%%})\n";fi
		fi
		if [ "${listonly}" = "1" ];then return;fi
		mv "${f%%}" "${f%%.*}.${mimeext}"
		fixed=$((fixed+1))
	fi
}

set_vars(){
	total="0"
	coll="0"
	fixed="0"
}

hlp(){
	printf " -A\trun in all sub-dirs of \$PWD\n"
	printf " -h\tprint this help\n"
	printf " -I\trun in single dir only\n"
	printf " -L\tlist only in \$PWD, no corrections\n"
	printf " -v\tverbose\n"
}

if [ -z "${1}" ];then hlp;exit;fi
while getopts "AILvh" OPT;do
	case "$OPT" in
		A) mode="all";;
		I) mode="correct";;
		L) mode="list";;
		v) export V="1";;
		h) hlp;exit;;
	esac
done

while true;do
	case "${mode}" in
		correct)
			listonly="0"
			set_vars
			for f in *;do mime_type_image;done
			if [ "${V}" = "1" ] && ! [ "${total}" = "0" ];then
				printf "Checked : ${total}\tCorrected : ${fixed}\tCollisions : ${coll}\tin : ${PWD}\n"
			elif ! [ "${total}" = "0" ];then
				printf "Checked : ${total}\tCorrected : ${fixed}\tCollisions : ${coll}\n"
			fi
			break;;
		list)
			listonly="1"
			set_vars
			for f in *;do mime_type_image;done
			if [ "${V}" = "1" ] && ! [ "${total}" = "0" ];then
				printf "Checked : ${total}\tCollisions : ${coll}\tin : ${PWD}\n"
			elif ! [ "${total}" = "0" ];then
				printf "Checked : ${total}\tCollisions : ${coll}\n"
			fi
			break;;
		all)
			#i give up on fixing this, if script renamed change below
			find . -type d -type d \( ! -name . \) -exec sh -c 'cd "{}" && mime-correct -I' \;
			break;;
	esac
done
