#!/bin/sh
#2.0.0
#2018-05-08

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

comp_dir="0"
comp_files="0"
orig_rm="0"

hlp() {
	printf " default will compress files passed in \$1\n"
	printf " -d\tcompress all directories\n"
	printf " -f\tcompress all files\n"
	printf " -h\tprint this help\n"
	printf " -s\tcompress \$1, delete after compressed\n"
	printf " -x\tcompress all files, delete original after compressed\n"
	printf " -z\tcompress all directories, delete original after compressed\n"
}

compress() {
	nice -19 lrztar -L 9 -H -z "${f%%}"
	if [ "${comp_rm}" = "1" ];then rm -r "${f%%}";fi
}

while true;do
	case "$1" in
		-d) comp_dir="1";shift;;
		-f) comp_files="1";shift;;
		-s) orig_rm="1";shift;;
		-x) comp_files="1";orig_rm="1";shift;;
		-z) comp_dir="1";orig_rm="1";shift;;
		-h) hlp;return;;
		*) break;;
	esac
done

if [ -n "${1}" ] && ! [ -e "${1}" ];then
	printf "Not a valid file : %s\n" "${1}"
elif [ -n "${1}" ] && [ -e "${1}" ];then
	f="${1%%}"
	compress
elif [ "${comp_dir}" = "1" ] || [ "${comp_files}" = "1" ];then
	for f in *; do
		if [ "${comp_dir}" = "1" ] && [ -d "${f}" ];then
			compress
		fi
		if [ "${comp_files}" = "1" ] && [ -f "${f}" ];then
			compress
		fi
	done
else
	printf "Something is broken\n";return
fi
