#!/usr/bin/env sh
#5.3.0
#2019-05-17

#Copyright (C) 2018,2019 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

zzz="1"
tst="0"
frm="0"
fls="0"

if [ -z "${1}" ];then "${0}" -h;exit;fi
while getopts "rltzh" OPT;do
	case "$OPT" in
		r) frm="1";;
		l) fls="1";;
		t) tst="1";;
		z) zzz="0";;
		h)
			printf " -h\tprint this help\n"
			printf " -l\tList found\n"
			printf " -r\tRemove found\n"
			printf " -t\tUse test dir '/tmp/test'\n"
			printf " -z\tDisable 'zzz' matching\n"
			exit;;
	esac
done

if [ "${tst}" = "0" ];then
	d="/mnt/data/hentai-processing/credits"
else
	d="/tmp/test/credits"
fi

find_credits()
{
	if [ "${fls}" = "1" ];then
		j=$(find . -iname "${1}" -exec ls -1A -- "{}" \;)
		if [ -n "${j}" ];then printf "*** Found 'POSSIBLE' credit files ***\n%s\n" "${j}";fi
	fi
	if [ "${frm}" = "1" ];then
		find . -type f -iname "${1}" -exec mv -v -- "{}" "${d}" \;
	fi
}

find_credits *credit*.j*pg
find_credits *credit*.png
if [ "${zzz}" = "1" ] || [ "${fls}" = "1" ];then
	find_credits *zzz*.j*pg
	find_credits *zzz*.png
fi
