#!/bin/sh
#4.6.0
#2018-09-21

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

found_rm="0"
found_ls="0"

url="0"
json="0"
txt="0"

hlp(){
	printf "General\n"
	printf " -h\tprint this help\n"
	printf " -l\tprint all files matching search patterns\n"
	printf " -r\tRemove enabled pattern files\n"
	printf " -R\tRemove all pattern files\n"
	printf "Patterns\n"
	printf " -A\tEnable remove for ALL patterns\n"
	printf " -j\tEnable remove for json\n"
	printf " -t\tEnable remove for txt\n"
	printf " -u\tEnable remove for url/mht\n"
}

find_junk(){
	if [ "${found_ls}" = "1" ];then
		j=$(find . -iname "${1}" -exec ls -1A -- "{}" \;)
		if [ -n "${j}" ];then printf "*** Found \"${1}\" files ***\n${j}\n";fi
	fi
	if [ "${found_rm}" = "1" ];then
		find . -type f -iname "${1}" -exec /usr/bin/trash-put -- '{}' \;
	fi
}

if [ -z "${1}" ];then hlp;return;fi
while true;do
	case "$1" in
		-r) found_rm="1";shift;;
		-l) found_ls="1";shift;;
		-R) found_rm="1";txt="1";json="1";url="1";shift;;
		-A) txt="1";json="1";url="1";shift;;
		-t) txt="1";shift;;
		-j) json="1";shift;;
		-u) url="1";shift;;
		-h) hlp;return;;
		*) break;;
	esac
done

find_junk desktop.ini
find_junk Thumbs.db
find_junk .DS_Store
find_junk __MACOSX
find_junk *.md5
find_junk *.nfo
find_junk *.sfv
find_junk .BridgeSort
find_junk _____padding_file*

if [ ${url} = "1" ] || [ "${found_ls}" = "1" ];then
	find_junk *.url
	find_junk *.mht
	find_junk *.htm
	find_junk *.html
fi
if [ ${txt} = "1" ] || [ "${found_ls}" = "1" ];then find_junk *.txt;fi
if [ ${json} = "1" ] || [ "${found_ls}" = "1" ];then find_junk *.json;fi
