#!/bin/sh
#4.7.1
#2018-12-08

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

act="ls"

url="0"
txt="0"
json="0"
other="0"

hlp(){
	printf "General\n"
	printf " -h\tprint this help\n"
	printf " -l\tprint all files matching search patterns\n"
	printf " -r\tRemove enabled pattern files\n"
	printf " -R\tRemove all pattern files\n"
	printf "Patterns\n"
	printf " -A\tEnable ALL patterns\n"
	printf " -j\tEnable json\n"
	printf " -o\tEnable md5/nfo/svf/bridgesort/padding_file\n"
	printf " -t\tEnable txt\n"
	printf " -u\tEnable url/mht/htm/html\n"
}

find_junk(){
	case "${act}" in
		ls)
			j=$(find . -iname ${1} -exec ls -1A -- "{}" \;)
			if [ -n "${j}" ];then printf "*** Found ${1} files ***\n${j}\n";fi
			;;
		rm)
			find . -type f -iname "${1}" -exec trash-put -- "{}" \;
			;;
	esac
}

if [ -z "${1}" ];then hlp;exit;fi
while true;do
	case "${1}" in
		-r) act="rm";shift;;
		-l) act="ls";shift;;
		-R) act="rm";txt="1";json="1";url="1";other="1";shift;;
		-A) txt="1";json="1";url="1";other="1";shift;;
		-t) txt="1";shift;;
		-j) json="1";shift;;
		-u) url="1";shift;;
		-o) other="1";shift;;
		-h) hlp;exit;;
		*) break;;
	esac
done

find_junk desktop.ini
find_junk Thumbs.db
find_junk .DS_Store
find_junk __MACOSX

if [ ${other} = "1" ] || [ "${act}" = "ls" ];then
	find_junk *.md5
	find_junk *.nfo
	find_junk *.sfv
	find_junk .BridgeSort
	find_junk _____padding_file*
fi

if [ ${url} = "1" ] || [ "${act}" = "ls" ];then
	find_junk *.url
	find_junk *.mht
	find_junk *.htm
	find_junk *.html
fi

if [ ${txt} = "1" ] || [ "${act}" = "ls" ];then find_junk *.txt;fi
if [ ${json} = "1" ] || [ "${act}" = "ls" ];then find_junk *.json;fi
