#!/bin/sh
#2.4.0
#2018-12-30

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#TODO
#improve hash check
#debug flags
#make less shit

num=$(ls -1A|wc -l)
int=$(seq -w -s ' ' ${num})
array="${int}"
files=$(ls -1A|sort -V)
mode="single"
while getopts "Bh" OPT;do
	case "$OPT" in
		b) mode="batch";;
		h)
			printf " -b\tBatch mode\n"
			printf " -h\tPrint this help\n"
			exit;;
	esac
done

case "${mode}" in
	single)
		for f in $files;do
			if [ -f "${f%%}" ];then
				array1=$(echo "$array"|cut -d ' ' -f 1)
				newname="${array1}.${f##*.}"
				if ! [ -f "${newname}" ];then
					mv -- "${f%%}" "${newname}"
				else
					a=$(md5sum "${f%%}")
					b=$(md5sum "${newname}")
					if [ "${a}" = "${b}" ];then
						printf "Same File not renaming\n"
					else
						printf "diferent files with same filename exist\n"
					fi
				fi
				array=$(echo "$array"|sed "s/[^ ]* //")
			fi
		done
		;;
	batch) find . -maxdepth 1 -type d \( ! -name . \) -exec cd -- '{}' && "${0}" \;;;
esac
