#!/bin/sh
#3.1.0
#2018-04-26

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

#faster, but i dont understand it
#md5sum * | sed -e 's/\([^ ]*\) \(.*\(\..*\)\)$/mv -v \2 \1\3/e'

#TODO
#hash collision check
#move if out of loop

sha1="0"
sha224="0"
sha256="0"
sha384="0"
sha512="0"
md5="0"

hlp() {
	printf " -1\tsha1\n"
	printf " -2\tsha224\n"
	printf " -3\tsha256\n"
	printf " -4\tsha384\n"
	printf " -5\tsha512\n"
	printf " -6\tmd5\n"
	printf " -h\tprint this help\n"
}

if [ -z "${1}" ];then hlp;return;fi

while true;do
	case "${1}" in
		-1) sha1="1";break;;
		-2) sha224="1";break;;
		-3) sha256="1";break;;
		-4) sha384="1";break;;
		-5) sha512="1";break;;
		-6) md5="1";break;;
		-h) hlp;return;;
		*) break;;
	esac
done

if [ "${sha1}" = "1" ];then h="/usr/bin/sha1sum";fi
if [ "${sha224}" = "1" ];then h="/usr/bin/sha224sum";fi
if [ "${sha256}" = "1" ];then h="/usr/bin/sha256sum";fi
if [ "${sha384}" = "1" ];then h="/usr/bin/sha384sum";fi
if [ "${sha512}" = "1" ];then h="/usr/bin/sha512sum";fi
if [ "${md5}" = "1" ];then h="/usr/bin/md5sum";fi

for f in *;do
	if [ -f "${f}" ];then
		"${h}" "${f}" | sed -e 's/\([^ ]*\) \(.*\(\..*\)\)$/mv -v \2 \1\3/e'
	fi
done
