#!/bin/sh
#1.1.0
#2018-10-14

#Copyright (C) 2018 Brandon Zorn, brandonzorn@cock.li
#
#This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

hlp(){
	printf " -b\tBatch mode\n"
	printf " -h\tPrint this help\n"
}

mode="single"
while true;do
	case "$1" in
		-b) mode="batch";shift;;
		-h) hlp;exit;;
		*) break;;
	esac
done

case "${mode}" in
	single)
		split2flac -of '@track - @title.@ext' ./
		;;
	batch)
		find . -maxdepth 1 -type d \( ! -name . \) -exec "cd '{}' && ${0}" \;
		;;
esac
