#!/usr/bin/env python3
# 5.1.0
# 2019-10-31

# Copyright (C) 2018,2019 Brandon Zorn <brandonzorn@cock.li>
#
# This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 3
#    as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <https://www.gnu.org/licenses/>.

import argparse
import os
import pyperclip


from utils import utils

args = None


def dl(link):
    cmd = 'youtube-dl --geo-bypass --no-overwrites --no-call-home --yes-playlist ' \
          '--audio-format best --audio-quality 0 --no-check-certificate'

    if args.audio:
        cmd += ' --extract-audio'

    cmd += ' ' + link

    print('\ndownloading: ', link)
    utils.run_cmd(cmd)


def main():
    global args
    parser = argparse.ArgumentParser()
    parser.add_argument('-a', '--audio',
                        action='store_true',
                        help='Only download audio')
    parser.add_argument('-u', "--url",
                        help='supply a video url, otherwise will get link from clipboard')
    group1 = parser.add_argument_group('Batch', 'NOT IMPLEMENTED')
    group1.add_argument('-b', '--batch',
                        action='store_true',
                        help='Download from batch file')
    group1.add_argument('-e', '--edit',
                        action='store_true',
                        help='edit batch file')
    group1.add_argument('-r', '--batch-rm',
                        action='store_true',
                        help='Delete batch file')
    args = parser.parse_args()

    utils.is_not_root()

    batch_list = '/tmp/ytdl.tmp'

    if args.edit:
        utils.edit_conf(batch_list)

    if args.batch_rm:
        if os.path.exists(batch_list):
            os.unlink(batch_list)
        exit(0)

    if args.batch:
        link = ''
        with open(batch_list) as fp:
            for link in fp:
                utils.link_check(link)
                dl(link)
    else:
        if args.url:
            link = args.url
        else:
            link = pyperclip.paste()

        utils.link_check(link)

    dl(link)


if __name__ == "__main__":
    main()
